// template/App.tsx
import React, { useState, useEffect } from 'react';
import { PredictionResult, AlertLog, PerformanceMetrics } from './types';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';

// API Base URL
const API_URL = 'http://127.0.0.1:5000/api';

const App: React.FC = () => {
    // State definition
    const [features, setFeatures] = useState<number[]>([]);
    const [featureNames, setFeatureNames] = useState<string[]>([]);
    const [result, setResult] = useState<PredictionResult | null>(null);
    const [loading, setLoading] = useState<boolean>(false);
    const [alerts, setAlerts] = useState<AlertLog[]>([]);
    const [history, setHistory] = useState<AlertLog[]>([]);
    const [metrics, setMetrics] = useState<PerformanceMetrics | null>(null);
    const [retraining, setRetraining] = useState<boolean>(false);
    const [selectedFiles, setSelectedFiles] = useState<FileList | null>(null);
    const [uploading, setUploading] = useState<boolean>(false);
    const [editingIndex, setEditingIndex] = useState<number | null>(null);
    const [editValue, setEditValue] = useState<string>('');
    const [activeTab, setActiveTab] = useState<'alerts' | 'history'>('alerts');

    // Initial Data Load
    useEffect(() => {
        fetchSampleData();
        fetchAlerts();
        fetchHistory();
        fetchMetrics();
        // Set up polling for alerts every 5 seconds
        const interval = setInterval(fetchAlerts, 5000);
        return () => clearInterval(interval);
    }, []);

    const fetchSampleData = async () => {
        try {
            const res = await fetch(`${API_URL}/sample`);
            const data = await res.json();
            setFeatures(data.features);
            setFeatureNames(data.feature_names);
        } catch (error) {
            console.error("Error fetching sample:", error);
        }
    };

    const fetchRandomData = async () => {
        try {
            const res = await fetch(`${API_URL}/random`);
            const data = await res.json();
            setFeatures(data.features);
            setFeatureNames(data.feature_names);
        } catch (error) {
            console.error("Error fetching random data:", error);
            // Fallback to generating client-side random data
            const newFeatures = features.map(() => Math.random() * 100000 - 50000);
            setFeatures(newFeatures);
        }
    };

    const fetchAttackData = async () => {
        try {
            const res = await fetch(`${API_URL}/simulate-attack`);
            const data = await res.json();
            setFeatures(data.features);
            setFeatureNames(data.feature_names);
        } catch (error) {
            console.error("Error fetching attack simulation data:", error);
            // Fallback to generating client-side attack-like data
            const newFeatures = features.map((_, i) => i % 3 === 0 ? Math.random() * 100000 : Math.random() * 1000);
            setFeatures(newFeatures);
        }
    };

    const fetchAlerts = async () => {
        try {
            const res = await fetch(`${API_URL}/alerts`);
            const data = await res.json();
            setAlerts(data);
        } catch (error) {
            console.error("Error fetching alerts:", error);
        }
    };

    const fetchHistory = async () => {
        try {
            const res = await fetch(`${API_URL}/history`);
            const data = await res.json();
            setHistory(data);
        } catch (error) {
            console.error("Error fetching history:", error);
        }
    };

    const fetchMetrics = async () => {
        try {
            const res = await fetch(`${API_URL}/performance`);
            const data = await res.json();
            setMetrics(data);
        } catch (error) {
            console.error("Error fetching metrics:", error);
        }
    };

    const handlePredict = async () => {
        setLoading(true);
        try {
            const res = await fetch(`${API_URL}/predict`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ features: features })
            });
            const data = await res.json();
            setResult(data);
            // Refresh alerts and history immediately
            fetchAlerts();
            fetchHistory();
        } catch (error) {
            console.error("Prediction error:", error);
        } finally {
            setLoading(false);
        }
    };

    const handleRetrain = async () => {
        if (!confirm("This will trigger the training script on the server. Continue?")) return;
        setRetraining(true);
        try {
            const res = await fetch(`${API_URL}/retrain`, { method: 'POST' });
            const data = await res.json();
            alert(data.message + (data.status === 'success' ? "\nPlease restart backend to load new model." : ""));
        } catch (error) {
            alert("Retraining failed check console.");
            console.error(error);
        } finally {
            setRetraining(false);
        }
    };

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setSelectedFiles(e.target.files);
    };

    const handleUploadAndRetrain = async () => {
        if (!selectedFiles || selectedFiles.length === 0) {
            alert("Please select at least one CSV file to upload.");
            return;
        }

        const formData = new FormData();
        for (let i = 0; i < selectedFiles.length; i++) {
            formData.append('files', selectedFiles[i]);
        }

        setUploading(true);
        try {
            const res = await fetch(`${API_URL}/upload-and-retrain`, {
                method: 'POST',
                body: formData
            });

            const data = await res.json();
            
            if (data.status === 'success') {
                alert("Model retrained successfully with uploaded data!");
                // Refresh metrics and sample data
                fetchMetrics();
                fetchSampleData();
            } else {
                alert(`Retraining failed: ${data.message}`);
            }
        } catch (error) {
            alert("Upload and retraining failed. Check console for details.");
            console.error(error);
        } finally {
            setUploading(false);
            setSelectedFiles(null);
        }
    };

    const handleFeatureChange = (index: number, value: string) => {
        const newFeatures = [...features];
        const numValue = parseFloat(value);
        if (!isNaN(numValue)) {
            newFeatures[index] = numValue;
        } else {
            newFeatures[index] = 0;
        }
        setFeatures(newFeatures);
    };

    const startEditing = (index: number, value: number) => {
        setEditingIndex(index);
        setEditValue(value.toString());
    };

    const saveEdit = (index: number) => {
        if (editingIndex === index) {
            handleFeatureChange(index, editValue);
            setEditingIndex(null);
        }
    };

    const cancelEdit = () => {
        setEditingIndex(null);
    };

    // Helper for color coding alerts
    const getLevelColor = (level: string) => {
        switch (level) {
            case 'High': return 'bg-red-100 text-red-800 border-red-200';
            case 'Medium': return 'bg-orange-100 text-orange-800 border-orange-200';
            case 'Low': return 'bg-yellow-100 text-yellow-800 border-yellow-200';
            default: return 'bg-green-100 text-green-800 border-green-200';
        }
    };

    // Prepare chart data
    const chartData = metrics ? [
        { name: 'Accuracy', value: metrics.accuracy * 100 },
        { name: 'Precision', value: metrics.precision * 100 },
        { name: 'Recall', value: metrics.recall * 100 },
        { name: 'F1 Score', value: metrics.f1_score * 100 },
    ] : [];

    return (
        <div className="min-h-screen p-6 bg-slate-50 font-sans">
            <header className="mb-8 flex justify-between items-center bg-white p-6 rounded-xl shadow-sm border border-slate-100">
                <div>
                    <h1 className="text-3xl font-bold text-slate-800 tracking-tight">DDoS Defense Shield</h1>
                    <p className="text-slate-500 mt-1">Real-time Traffic Analysis & Threat Intelligence</p>
                </div>
                <div className="flex gap-4">
                     <button 
                        onClick={handleRetrain}
                        disabled={retraining}
                        className={`px-4 py-2 rounded-lg font-medium transition-colors ${retraining ? 'bg-gray-300' : 'bg-indigo-600 hover:bg-indigo-700 text-white'}`}
                    >
                        {retraining ? 'Training...' : 'Retrain Model'}
                    </button>
                    <div className="px-4 py-2 bg-green-50 text-green-700 rounded-lg border border-green-100 font-medium">
                        System Active
                    </div>
                </div>
            </header>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                
                {/* Left Column: Input & Prediction */}
                <div className="lg:col-span-8 space-y-8">
                    
                    {/* File Upload Panel */}
                    <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100">
                        <h2 className="text-xl font-bold text-slate-800 mb-4">Model Retraining</h2>
                        <div className="mb-4">
                            <label className="block text-sm font-medium text-slate-700 mb-2">
                                Upload CSV Files for Retraining
                            </label>
                            <input
                                type="file"
                                accept=".csv"
                                multiple
                                onChange={handleFileChange}
                                className="block w-full text-sm text-slate-500
                                    file:mr-4 file:py-2 file:px-4
                                    file:rounded-lg file:border-0
                                    file:text-sm file:font-semibold
                                    file:bg-indigo-50 file:text-indigo-700
                                    hover:file:bg-indigo-100"
                            />
                            {selectedFiles && (
                                <p className="mt-2 text-sm text-slate-500">
                                    Selected {selectedFiles.length} file(s)
                                </p>
                            )}
                        </div>
                        <button
                            onClick={handleUploadAndRetrain}
                            disabled={uploading || !selectedFiles || selectedFiles.length === 0}
                            className={`w-full py-2 rounded-lg font-medium transition-colors ${
                                uploading || !selectedFiles || selectedFiles.length === 0
                                    ? 'bg-gray-300 cursor-not-allowed'
                                    : 'bg-indigo-600 hover:bg-indigo-700 text-white'
                            }`}
                        >
                            {uploading ? 'Uploading and Retraining...' : 'Upload and Retrain Model'}
                        </button>
                    </div>

                    {/* Prediction Panel */}
                    <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100">
                        <div className="flex justify-between items-center mb-6">
                            <h2 className="text-xl font-bold text-slate-800">Traffic Analyzer</h2>
                            <div className="flex gap-2">
                                <button 
                                    onClick={fetchSampleData}
                                    className="text-sm text-indigo-600 hover:text-indigo-800 font-medium"
                                >
                                    ↺ Reset to Sample Data
                                </button>
                                <button 
                                    onClick={fetchRandomData}
                                    className="text-sm text-indigo-600 hover:text-indigo-800 font-medium"
                                >
                                    🎲 Random Data
                                </button>
                                <button 
                                    onClick={fetchAttackData}
                                    className="text-sm text-red-600 hover:text-red-800 font-medium"
                                >
                                    ⚔️ Simulate Attack
                                </button>
                            </div>
                        </div>
                        
                        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200 mb-6 max-h-96 overflow-y-auto">
                            <p className="text-xs text-slate-500 mb-2 font-mono">Raw Feature Vector ({features.length} features)</p>
                            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-2">
                                {features.map((value, index) => (
                                    <div key={index} className="flex items-center text-xs">
                                        <span className="text-slate-500 w-16 truncate mr-1" title={featureNames[index] || `Feature ${index}`}>{
                                            featureNames[index] ? 
                                            featureNames[index].length > 10 ? 
                                            featureNames[index].substring(0, 10) + '...' : 
                                            featureNames[index] : 
                                            `Feat ${index}`
                                        }</span>
                                        {editingIndex === index ? (
                                            <div className="flex">
                                                <input
                                                    type="number"
                                                    value={editValue}
                                                    onChange={(e) => setEditValue(e.target.value)}
                                                    className="w-20 px-1 py-0.5 text-xs border rounded"
                                                    autoFocus
                                                    onKeyDown={(e) => {
                                                        if (e.key === 'Enter') saveEdit(index);
                                                        if (e.key === 'Escape') cancelEdit();
                                                    }}
                                                />
                                                <button 
                                                    onClick={() => saveEdit(index)}
                                                    className="ml-1 px-1 bg-green-500 text-white rounded"
                                                >
                                                    ✓
                                                </button>
                                                <button 
                                                    onClick={cancelEdit}
                                                    className="ml-1 px-1 bg-red-500 text-white rounded"
                                                >
                                                    ✕
                                                </button>
                                            </div>
                                        ) : (
                                            <span 
                                                className="font-mono w-24 truncate cursor-pointer hover:bg-slate-200 px-1 py-0.5 rounded"
                                                onClick={() => startEditing(index, value)}
                                                title={value.toString()}
                                            >
                                                {value.toFixed(2)}
                                            </span>
                                        )}
                                    </div>
                                ))}
                            </div>
                        </div>

                        <button
                            onClick={handlePredict}
                            disabled={loading}
                            className={`w-full py-4 rounded-lg text-white font-bold text-lg shadow-lg transition-all transform active:scale-95 ${loading ? 'bg-slate-400' : 'bg-indigo-600 hover:bg-indigo-700 hover:shadow-xl'}`}
                        >
                            {loading ? 'Analyzing Traffic...' : 'Analyze Traffic Pattern'}
                        </button>
                    </div>

                    {/* Result Display */}
                    {result && (
                        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100 animate-fade-in">
                            <h2 className="text-xl font-bold text-slate-800 mb-4">Analysis Result</h2>
                            
                            <div className={`p-6 rounded-xl border-l-8 flex items-center justify-between ${result.predicted_label === 'BENIGN' ? 'bg-green-50 border-green-500' : 'bg-red-50 border-red-500'}`}>
                                <div>
                                    <h3 className="text-2xl font-extrabold uppercase tracking-wider mb-1">
                                        {result.predicted_label}
                                    </h3>
                                    <p className="text-slate-600">
                                        Confidence: <span className="font-mono font-bold">{(result.confidence * 100).toFixed(2)}%</span>
                                    </p>
                                </div>
                                <div className="text-right">
                                    <span className="block text-xs uppercase text-slate-500 font-bold mb-1">Threat Level</span>
                                    <span className={`inline-block px-4 py-1 rounded-full text-sm font-bold border ${getLevelColor(result.threat_level)}`}>
                                        {result.threat_level}
                                    </span>
                                </div>
                            </div>
                        </div>
                    )}

                    {/* Performance Metrics Chart */}
                    <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100">
                         <h2 className="text-xl font-bold text-slate-800 mb-4">Model Performance (RF)</h2>
                         <div className="h-64 w-full">
                            <ResponsiveContainer width="100%" height="100%">
                                <BarChart data={chartData}>
                                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                                    <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#64748b'}} />
                                    <YAxis hide />
                                    <Tooltip 
                                        cursor={{fill: '#f1f5f9'}}
                                        contentStyle={{borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)'}} 
                                    />
                                    <Bar dataKey="value" fill="#6366f1" radius={[4, 4, 0, 0]} barSize={50} label={{ position: 'top', fill: '#64748b', fontSize: 12 }} />
                                </BarChart>
                            </ResponsiveContainer>
                         </div>
                    </div>
                </div>

                {/* Right Column: Alert Logs and History */}
                <div className="lg:col-span-4 space-y-8">
                    <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100 h-full max-h-[800px] flex flex-col">
                        <div className="flex items-center justify-between mb-6">
                            <h2 className="text-xl font-bold text-slate-800">Threat Intelligence</h2>
                            <span className="text-xs bg-red-100 text-red-600 px-2 py-1 rounded-full font-bold animate-pulse">LIVE</span>
                        </div>

                        {/* Tabs for Alerts and History */}
                        <div className="flex border-b border-slate-200 mb-4">
                            <button
                                className={`py-2 px-4 font-medium text-sm ${activeTab === 'alerts' ? 'border-b-2 border-indigo-500 text-indigo-600' : 'text-slate-500'}`}
                                onClick={() => setActiveTab('alerts')}
                            >
                                Recent Alerts
                            </button>
                            <button
                                className={`py-2 px-4 font-medium text-sm ${activeTab === 'history' ? 'border-b-2 border-indigo-500 text-indigo-600' : 'text-slate-500'}`}
                                onClick={() => setActiveTab('history')}
                            >
                                Detection History
                            </button>
                        </div>

                        <div className="flex-1 overflow-y-auto space-y-3 pr-2 custom-scrollbar">
                            {activeTab === 'alerts' ? (
                                <>
                                    <h3 className="text-md font-bold text-slate-700">Recent Alerts (Live)</h3>
                                    {alerts.length === 0 ? (
                                        <div className="text-center text-slate-400 py-10">
                                            <p>No threats detected yet.</p>
                                        </div>
                                    ) : (
                                        alerts.map((alert, idx) => (
                                            <div key={idx} className="p-4 rounded-lg bg-slate-50 border border-slate-100 hover:bg-slate-100 transition-colors">
                                                <div className="flex justify-between items-start mb-2">
                                                    <span className={`px-2 py-0.5 rounded text-xs font-bold border ${getLevelColor(alert.level)}`}>
                                                        {alert.level} PRIORITY
                                                    </span>
                                                    <span className="text-xs text-slate-400">{alert.timestamp.split(' ')[1]}</span>
                                                </div>
                                                <p className="font-bold text-slate-800">{alert.type}</p>
                                                <p className="text-xs text-slate-500 mt-1">Confidence Score: {(alert.confidence * 100).toFixed(1)}%</p>
                                            </div>
                                        ))
                                    )}
                                </>
                            ) : (
                                <>
                                    <h3 className="text-md font-bold text-slate-700">Detection History</h3>
                                    {history.length === 0 ? (
                                        <div className="text-center text-slate-400 py-10">
                                            <p>No detection history available.</p>
                                        </div>
                                    ) : (
                                        history.map((record, idx) => (
                                            <div key={idx} className="p-4 rounded-lg bg-slate-50 border border-slate-100 hover:bg-slate-100 transition-colors">
                                                <div className="flex justify-between items-start mb-2">
                                                    <span className={`px-2 py-0.5 rounded text-xs font-bold border ${getLevelColor(record.level)}`}>
                                                        {record.level !== 'None' ? record.level + ' PRIORITY' : 'NORMAL'}
                                                    </span>
                                                    <span className="text-xs text-slate-400">{record.timestamp.split(' ')[1]}</span>
                                                </div>
                                                <p className="font-bold text-slate-800">{record.type}</p>
                                                <p className="text-xs text-slate-500 mt-1">Confidence Score: {(record.confidence * 100).toFixed(1)}%</p>
                                            </div>
                                        ))
                                    )}
                                </>
                            )}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default App;

// App.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue';
import { api } from './services/api';
import { PerformanceMetrics, PredictionResult, LogEntry } from './types';
import StatCard from './components/StatCard.vue';
import RadarChart from './components/RadarChart.vue';

type PredictionResultWithTimestamp = PredictionResult & { timestamp?: string };
type RealtimeLevel = 'Low' | 'Medium' | 'High';

// --- State ---
const performanceData = ref<PerformanceMetrics | null>(null);
const isLoadingPerf = ref(true);
const isAnalyzing = ref(false);
const isRetraining = ref(false);
const predictionResult = ref<PredictionResultWithTimestamp | null>(null);
const logs = ref<LogEntry[]>([
  { id: 1, timestamp: new Date().toLocaleTimeString(), message: "[SYSTEM] IDS initialized successfully...", type: "success" },
  { id: 2, timestamp: new Date().toLocaleTimeString(), message: "[SYSTEM] Connected to RF Model (78 features)...", type: "info" }
]);
const fileInput = ref<HTMLInputElement | null>(null);

// --- Realtime intensity (10s sliding window, ✅ BENIGN 不计入) ---
const isAttackRunning = ref(false);
const windowMs = ref(10000);
const realtimeCount = ref(0); // ✅ 只统计非BENIGN次数
const realtimeLevel = ref<RealtimeLevel>('Low');
const streamRunId = ref(0);

const sleep = (ms: number) => new Promise<void>(r => setTimeout(r, ms));

const calcLevel = (count: number, thresholds?: { low_max: number; medium_max: number }): RealtimeLevel => {
  const lowMax = thresholds?.low_max ?? 5;
  const medMax = thresholds?.medium_max ?? 10;
  if (count <= lowMax) return 'Low';
  if (count <= medMax) return 'Medium';
  return 'High';
};

// ✅ 展示用 threat：攻击运行时用 realtimeLevel，否则用模型 threat_level
const displayThreat = computed(() => {
  if (isAttackRunning.value) return realtimeLevel.value;
  return (predictionResult.value?.threat_level ?? 'Idle') as any;
});

// --- Actions ---

// Load Performance Metrics
const loadPerformance = async () => {
  isLoadingPerf.value = true;
  try {
    const data = await api.getPerformance();
    performanceData.value = data;
  } catch (error) {
    console.warn("Load failed", error);
    performanceData.value = null;
  } finally {
    isLoadingPerf.value = false;
  }
};

// Handle Log Adding (model result)
const addLog = (res: PredictionResult) => {
  const newLog: LogEntry = {
    id: Date.now(),
    timestamp: new Date().toLocaleTimeString(),
    message: `DETECTED: `,
    label: res.predicted_label,
    confidence: `(Conf: ${(res.confidence * 100).toFixed(1)}%)`,
    type: res.threat_level === 'None' ? 'success' : 'danger',
    threat_level: res.threat_level,
    probabilities: res.probabilities
  };
  logs.value.unshift(newLog);
};

// Simulate Traffic
const simulateTraffic = async (type: 'normal' | 'attack' | 'random') => {
  isAnalyzing.value = true;
  const myRun = ++streamRunId.value;

  try {
    const data: any = await api.getTrafficData(type);
    const stream = Array.isArray(data?.stream) ? data.stream : null;

    // --- ATTACK: play a 10s plan, update intensity in real time (✅ BENIGN 不计入) ---
    if (type === 'attack' && stream && stream.length > 0) {
      isAttackRunning.value = true;

      const thresholds = data.thresholds ?? { low_max: 5, medium_max: 10 };
      const winSec = Number(data.time_window_seconds ?? 10);
      windowMs.value = Math.max(1000, winSec * 1000);

      // ✅ 只记录“非BENIGN”的事件时间戳
      const nonBenignTimes: number[] = [];
      realtimeCount.value = 0;
      realtimeLevel.value = 'Low';

      logs.value.unshift({
        id: Date.now(),
        timestamp: new Date().toLocaleTimeString(),
        message: `[SIM] Attack plan started (mode=${data.mode ?? 'N/A'}, total=${data.attack_frequency ?? stream.length}, window=${winSec}s). NOTE: BENIGN will NOT be counted.`,
        type: 'info'
      });

      // ✅ 定时器：处理衰减（只对 nonBenignTimes）
      const refreshInterval = 200;
      const intensityTimer = setInterval(() => {
        const now = Date.now();
        while (nonBenignTimes.length && now - nonBenignTimes[0] > windowMs.value) nonBenignTimes.shift();

        const newCount = nonBenignTimes.length;
        const newLevel = calcLevel(newCount, thresholds);

        if (streamRunId.value === myRun) {
          realtimeCount.value = newCount;
          realtimeLevel.value = newLevel;
        }
      }, refreshInterval);

      let lastLevel: RealtimeLevel = realtimeLevel.value;

      const start = Date.now();

      // ✅ 按 at_ms 定点触发
      for (const sample of stream) {
        if (streamRunId.value !== myRun) break;

        const target = start + Number(sample.at_ms ?? 0);
        const wait = Math.max(0, target - Date.now());
        await sleep(wait);

        // 预测（保持原流程）
        const result = await api.predict(sample.features);

        predictionResult.value = {
          ...result,
          timestamp: new Date(sample.ts ?? Date.now()).toLocaleTimeString()
        };
        addLog(result);

        // ✅ BENIGN 不计入“10秒内攻击次数”
        const pred = String(result.predicted_label ?? '').trim().toUpperCase();
        const isBenign = (pred === 'BENIGN');

        if (!isBenign) {
          const now = Date.now();
          nonBenignTimes.push(now);

          // 立刻刷新一次（不等定时器）
          while (nonBenignTimes.length && now - nonBenignTimes[0] > windowMs.value) nonBenignTimes.shift();
          realtimeCount.value = nonBenignTimes.length;

          const newLevel = calcLevel(realtimeCount.value, thresholds);
          realtimeLevel.value = newLevel;

          if (newLevel !== lastLevel) {
            lastLevel = newLevel;
            logs.value.unshift({
              id: Date.now() + Math.random(),
              timestamp: new Date().toLocaleTimeString(),
              message: `[ALERT] Traffic intensity escalated to <b>${newLevel}</b> (10s non-BENIGN count=${realtimeCount.value})`,
              type: newLevel === 'High' ? 'danger' : 'info'
            });
          }
        }
      }

      logs.value.unshift({
        id: Date.now() + 1,
        timestamp: new Date().toLocaleTimeString(),
        message: `[SIM] Attack plan finished. Waiting for 10s window to decay...`,
        type: 'info'
      });

      // ✅ 等到 10 秒窗口自然衰减到 0（只看非BENIGN）
      const decayStart = Date.now();
      while (streamRunId.value === myRun) {
        const now = Date.now();
        while (nonBenignTimes.length && now - nonBenignTimes[0] > windowMs.value) nonBenignTimes.shift();
        if (nonBenignTimes.length === 0) break;

        if (now - decayStart > windowMs.value + 1000) break;
        await sleep(refreshInterval);
      }

      clearInterval(intensityTimer);
      isAttackRunning.value = false;

      logs.value.unshift({
        id: Date.now() + 2,
        timestamp: new Date().toLocaleTimeString(),
        message: `[SIM] Intensity window cleared (10s non-BENIGN count=${realtimeCount.value}, level=${realtimeLevel.value}).`,
        type: 'info'
      });
    } else {
      // --- NORMAL / RANDOM: single shot as before ---
      const result = await api.predict(data.features);
      predictionResult.value = result;
      addLog(result);

      isAttackRunning.value = false;
      realtimeCount.value = 0;
      realtimeLevel.value = 'Low';
    }
  } catch (error: any) {
    console.error(error);
    const msg = error.name === 'AbortError'
      ? "⚠️ Request Timed Out! Server took too long."
      : `❌ Error: ${error.message}`;
    alert(msg);

    isAttackRunning.value = false;
    realtimeCount.value = 0;
    realtimeLevel.value = 'Low';
  } finally {
    if (streamRunId.value === myRun) isAnalyzing.value = false;
  }
};

// Upload & Retrain
const handleRetrain = async () => {
  const file = fileInput.value?.files?.[0];
  if (!file) {
    alert("Please select a CSV file first!");
    return;
  }

  isRetraining.value = true;
  try {
    const res = await api.retrain(file);
    alert("✅ " + res.message);
    await loadPerformance();
    if (fileInput.value) fileInput.value.value = '';
  } catch (error: any) {
    const msg = error.name === 'AbortError'
      ? "⚠️ Training Timeout! Dataset might be too large."
      : `❌ Training Failed: ${error.message}`;
    alert(msg);
  } finally {
    isRetraining.value = false;
  }
};

onMounted(() => {
  loadPerformance();
});
</script>

<template>
  <div class="w-full min-h-screen p-6 flex flex-col">
    <header class="flex flex-col md:flex-row justify-between items-center mb-6 pb-4 border-b border-gray-300">
      <div class="mb-4 md:mb-0 text-center md:text-left">
        <h2 class="text-3xl font-bold text-primary flex items-center gap-2">
          <i class="fas fa-shield-virus"></i> DDoS Defense Shield
        </h2>
        <small class="text-gray-500 font-medium">Real-time Network Traffic Analysis & Threat Intelligence</small>
      </div>
      <span class="bg-green-100 text-green-700 border border-green-200 px-3 py-1.5 rounded text-sm font-semibold flex items-center">
        System Active <i class="fas fa-satellite-dish fa-spin ml-2"></i>
      </span>
    </header>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
      <StatCard
        title="Accuracy"
        :value="performanceData?.accuracy"
        color-class="text-green-600"
        :is-loading="isLoadingPerf"
      />
      <StatCard
        title="Precision"
        :value="performanceData?.precision"
        color-class="text-blue-600"
        :is-loading="isLoadingPerf"
      />
      <StatCard
        title="Recall"
        :value="performanceData?.recall"
        color-class="text-orange-500"
        :is-loading="isLoadingPerf"
      />
      <StatCard
        title="FPR"
        :value="performanceData?.FPR"
        color-class="text-red-600"
        :is-loading="isLoadingPerf"
      />
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-12 gap-6 flex-1">
      <div class="lg:col-span-3">
        <div class="bg-white border border-gray-200 shadow-sm rounded-lg p-5 h-full">
          <h5 class="text-gray-800 border-b border-gray-200 pb-2 mb-4 font-bold flex items-center gap-2">
            <i class="fas fa-network-wired text-primary"></i> Traffic Simulator
          </h5>
          <p class="text-gray-500 text-sm mb-4">Inject simulated packets to test IDS response.</p>

          <div class="space-y-3">
            <button
              @click="simulateTraffic('normal')"
              :disabled="isAnalyzing"
              class="w-full py-2.5 px-4 bg-white border border-primary text-primary font-semibold uppercase tracking-wide hover:bg-primary hover:text-white transition-colors duration-300 rounded disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              <i class="fas fa-check-circle"></i> Normal Traffic
            </button>
            <button
              @click="simulateTraffic('attack')"
              :disabled="isAnalyzing"
              class="w-full py-2.5 px-4 bg-white border border-red-500 text-red-500 font-semibold uppercase tracking-wide hover:bg-red-500 hover:text-white transition-colors duration-300 rounded disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              <i class="fas fa-biohazard"></i> DDoS Attack
            </button>
          </div>

          <div v-if="isAnalyzing" class="mt-4 text-center text-primary font-bold animate-pulse text-sm">
            <i class="fas fa-spinner fa-spin mr-1"></i> Analyzing Features...
          </div>
        </div>
      </div>

      <div class="lg:col-span-6 flex flex-col gap-4 min-h-0">
        <div class="bg-white border border-gray-200 shadow-sm rounded-lg p-5">
          <div class="flex justify-between items-start">
            <div class="flex-1">
              <h6 class="text-gray-400 text-xs uppercase font-bold">Last Detection Result:</h6>
              <h3
                class="text-3xl font-bold mt-1"
                :class="{
                  'text-gray-800': !predictionResult && !isAttackRunning,
                  'text-green-600': displayThreat === 'None' || displayThreat === 'Low',
                  'text-orange-500': displayThreat === 'Medium',
                  'text-red-600': displayThreat === 'High',
                }"
              >
                {{ predictionResult?.predicted_label || 'Waiting for input...' }}
              </h3>

              <div v-if="predictionResult" class="mt-2 text-sm text-gray-600 space-y-1">
                <div>
                  <span class="font-semibold">Confidence:</span>
                  <span class="font-mono">{{ (predictionResult.confidence * 100).toFixed(2) }}%</span>
                </div>
                <div v-if="predictionResult.timestamp">
                  <span class="font-semibold">Detected at:</span>
                  <span class="font-mono">{{ predictionResult.timestamp }}</span>
                </div>
              </div>
            </div>

            <span
              class="px-4 py-2 rounded-full text-sm font-semibold shadow-sm whitespace-nowrap"
              :class="{
                'bg-gray-200 text-gray-700': !predictionResult && !isAttackRunning,
                'bg-green-100 text-green-800': displayThreat === 'None' || displayThreat === 'Low',
                'bg-orange-100 text-orange-800': displayThreat === 'Medium',
                'bg-red-100 text-red-800': displayThreat === 'High',
              }"
            >
              Status: {{ displayThreat }}
              <span v-if="isAttackRunning" class="ml-2 text-xs opacity-70">(10s non-BENIGN: {{ realtimeCount }})</span>
            </span>
          </div>

          <div v-if="predictionResult?.probabilities && Object.keys(predictionResult.probabilities).length > 1" class="mt-4 pt-4 border-t border-gray-200">
            <h6 class="text-gray-500 text-xs uppercase font-bold mb-2">Probability Distribution:</h6>
            <div class="space-y-2">
              <div v-for="(prob, label) in predictionResult.probabilities" :key="label" class="flex items-center gap-3">
                <span class="text-xs font-medium w-36 truncate" :title="label">{{ label }}</span>
                <div class="flex-1 bg-gray-200 rounded-full h-3">
                  <div
                    class="h-3 rounded-full transition-all"
                    :class="{
                      'bg-green-500': predictionResult.predicted_label === label && predictionResult.threat_level === 'None',
                      'bg-orange-500': predictionResult.predicted_label === label && predictionResult.threat_level === 'Medium',
                      'bg-red-500': predictionResult.predicted_label === label && predictionResult.threat_level === 'High',
                      'bg-blue-400': predictionResult.predicted_label !== label
                    }"
                    :style="{ width: `${prob * 100}%` }"
                  ></div>
                </div>
                <span class="text-xs font-mono w-14 text-right">{{ (prob * 100).toFixed(1) }}%</span>
              </div>
            </div>
          </div>
        </div>

        <div class="bg-white border border-gray-200 shadow-sm rounded-lg p-5 flex-1 flex flex-col min-h-0">
          <h5 class="text-gray-800 border-b border-gray-200 pb-2 mb-2 font-bold flex items-center gap-2">
            <i class="fas fa-terminal text-primary"></i> Live Threat Logs
          </h5>
          <div class="bg-gray-50 border border-gray-200 rounded p-4 flex-1 overflow-y-auto font-mono text-sm">
            <div v-for="log in logs" :key="log.id" class="mb-3 pb-2 border-b border-gray-200 last:border-b-0" :class="log.type === 'success' ? 'text-green-600' : (log.type === 'info' ? 'text-gray-500' : 'text-red-600')">
              <div class="mb-1">
                <span class="opacity-70">[{{ log.timestamp }}]</span>
                <span v-html="log.message"></span>
                <b v-if="log.label">{{ log.label }}</b>
                <span v-if="log.confidence" class="ml-1 opacity-80">{{ log.confidence }}</span>
                <span v-if="log.threat_level" class="ml-2 px-2 py-0.5 rounded text-xs font-semibold"
                  :class="{
                    'bg-green-100 text-green-800': log.threat_level === 'None' || log.threat_level === 'Low',
                    'bg-orange-100 text-orange-800': log.threat_level === 'Medium',
                    'bg-red-100 text-red-800': log.threat_level === 'High'
                  }">
                  {{ log.threat_level }}
                </span>
              </div>

              <div v-if="log.probabilities && Object.keys(log.probabilities).length > 1" class="ml-6 text-xs opacity-70 space-y-0.5">
                <div v-for="(prob, label) in log.probabilities" :key="label" class="flex items-center gap-2">
                  <span class="w-32 truncate">{{ label }}:</span>
                  <div class="flex-1 bg-gray-200 rounded-full h-2 max-w-[150px]">
                    <div class="bg-current h-2 rounded-full transition-all" :style="{ width: `${prob * 100}%` }"></div>
                  </div>
                  <span class="w-12 text-right">{{ (prob * 100).toFixed(1) }}%</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="lg:col-span-3 flex flex-col gap-4 h-full">
        <div class="bg-white border border-gray-200 shadow-sm rounded-lg p-5">
          <h5 class="text-gray-800 border-b border-gray-200 pb-2 mb-3 font-bold flex items-center gap-2">
            <i class="fas fa-sync text-primary"></i> Model Retraining
          </h5>
          <div class="mb-3">
            <label class="block text-gray-500 text-xs font-bold uppercase mb-1">Upload CSV Dataset:</label>
            <input
              type="file"
              ref="fileInput"
              class="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded file:border-0 file:text-sm file:font-semibold file:bg-gray-700 file:text-white hover:file:bg-gray-800 cursor-pointer border border-gray-300 rounded"
            >
          </div>
          <button
            @click="handleRetrain"
            :disabled="isRetraining"
            class="w-full py-2 px-4 border border-primary text-primary hover:bg-primary hover:text-white rounded transition-colors duration-300 text-sm font-semibold flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <span v-if="isRetraining" class="inline-block w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin"></span>
            <span v-else><i class="fas fa-upload"></i></span>
            {{ isRetraining ? 'Training...' : 'Upload & Retrain' }}
          </button>
        </div>

        <div class="flex-1 min-h-[300px]">
          <RadarChart :data="performanceData" />
        </div>
      </div>
    </div>
  </div>
</template>
